# Generated by Django 4.1.1 on 2022-09-23 22:35

import autoslug.fields
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AdBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=300)),
                ('image', models.ImageField(upload_to='ads-banners')),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='brands')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='image-banner')),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('afterPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('isDiscount', models.BooleanField(default=False)),
                ('isNew', models.BooleanField(default=False)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
                ('availability', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('sku', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
                ('rating', models.SmallIntegerField()),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product', to='store.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product', to='store.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('discount', models.PositiveSmallIntegerField()),
                ('isPercentage', models.BooleanField(default=False)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=300)),
                ('image', models.ImageField(upload_to='video-banners')),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CaseFeatures',
            fields=[
                ('product', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='caseFeatures', serialize=False, to='store.product')),
                ('watt', models.CharField(blank=True, max_length=10, null=True)),
                ('caseFans', models.CharField(blank=True, max_length=10, null=True)),
                ('bundled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CoolingFeatures',
            fields=[
                ('product', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='coolingFeatures', serialize=False, to='store.product')),
                ('pcCooling', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GraphicsCardFeatures',
            fields=[
                ('product', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='graphicsCardFeatures', serialize=False, to='store.product')),
                ('chipset', models.CharField(blank=True, max_length=20, null=True)),
                ('gpuMemory', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonitorFeatures',
            fields=[
                ('product', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='monitorFeatures', serialize=False, to='store.product')),
                ('displayRes', models.CharField(blank=True, max_length=12, null=True)),
                ('screenSize', models.CharField(blank=True, max_length=5, null=True)),
                ('panelType', models.CharField(blank=True, max_length=5, null=True)),
                ('responseTime', models.CharField(blank=True, max_length=5, null=True)),
                ('refreshRate', models.CharField(blank=True, max_length=5, null=True)),
                ('flatCurved', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MotherBoardFeatures',
            fields=[
                ('product', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='motherBoardFeatures', serialize=False, to='store.product')),
                ('socket', models.CharField(blank=True, max_length=20, null=True)),
                ('series', models.CharField(blank=True, max_length=50, null=True)),
                ('generation', models.CharField(blank=True, max_length=50, null=True)),
                ('cores', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotebookFeatures',
            fields=[
                ('product', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='notebook', serialize=False, to='store.product')),
                ('display', models.CharField(blank=True, max_length=20, null=True)),
                ('graphicsCard', models.CharField(blank=True, max_length=20, null=True)),
                ('ram', models.CharField(blank=True, max_length=20, null=True)),
                ('panel', models.CharField(blank=True, max_length=20, null=True)),
                ('processor', models.CharField(blank=True, max_length=20, null=True)),
                ('refreshRate', models.CharField(blank=True, max_length=20, null=True)),
                ('storage', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PowerSupplyFeatures',
            fields=[
                ('product', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='powerSupplyFeatures', serialize=False, to='store.product')),
                ('watt', models.CharField(blank=True, max_length=10, null=True)),
                ('rating', models.CharField(blank=True, max_length=10, null=True)),
                ('fmodular', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessorFeatures',
            fields=[
                ('product', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='processorFeatures', serialize=False, to='store.product')),
                ('socket', models.CharField(blank=True, max_length=20, null=True)),
                ('series', models.CharField(blank=True, max_length=50, null=True)),
                ('generation', models.CharField(blank=True, max_length=50, null=True)),
                ('cores', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RamFeatures',
            fields=[
                ('product', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='ramFeatures', serialize=False, to='store.product')),
                ('capacity', models.CharField(blank=True, max_length=6, null=True)),
                ('memoryType', models.CharField(blank=True, max_length=7, null=True)),
                ('speed', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StorageFeatures',
            fields=[
                ('product', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='storage', serialize=False, to='store.product')),
                ('capacity', models.CharField(blank=True, max_length=6, null=True)),
                ('formfactor', models.CharField(blank=True, max_length=10, null=True)),
                ('interface', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likedDate', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.product')),
            ],
            options={
                'ordering': ['products'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='subCategory')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('unitPrice', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
            options={
                'ordering': ['cart'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageOne', models.ImageField(blank=True, upload_to='products')),
                ('imageTwo', models.ImageField(blank=True, upload_to='products')),
                ('imageThree', models.ImageField(blank=True, upload_to='products')),
                ('imageFour', models.ImageField(blank=True, upload_to='products')),
                ('imageFive', models.ImageField(blank=True, upload_to='products')),
                ('imageSix', models.ImageField(blank=True, upload_to='products')),
                ('imageSeven', models.ImageField(blank=True, upload_to='products')),
                ('imageEight', models.ImageField(blank=True, upload_to='products')),
                ('imageNine', models.ImageField(blank=True, upload_to='products')),
                ('imageTen', models.ImageField(blank=True, upload_to='products')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
            options={
                'ordering': ['product'],
            },
        ),
        migrations.CreateModel(
            name='ProductBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='product-banner')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='subCategory',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='category', chained_model_field='collection', on_delete=django.db.models.deletion.CASCADE, to='store.subcategory'),
        ),
        migrations.CreateModel(
            name='FeaturedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='BrandBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='brand-banners')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('lineOne', models.CharField(max_length=255)),
                ('lineTwo', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
