# Generated by Django 4.1.1 on 2022-09-24 01:10

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='collections'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subCategory',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='category', chained_model_field='category', on_delete=django.db.models.deletion.CASCADE, to='store.subcategory'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, upload_to='subCollection'),
        ),
    ]
