# Generated by Django 4.1.1 on 2022-09-24 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_image_alter_product_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebookfeatures',
            name='display',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notebookfeatures',
            name='graphicsCard',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notebookfeatures',
            name='panel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notebookfeatures',
            name='processor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notebookfeatures',
            name='ram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notebookfeatures',
            name='refreshRate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notebookfeatures',
            name='storage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
