# Generated by Django 4.1.1 on 2022-09-24 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_notebookfeatures_display_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videobanner',
            name='image',
        ),
    ]
