# Generated by Django 4.1.1 on 2022-10-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_brandbanner_product_brandbanner_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videobanner',
            name='url',
            field=models.FileField(upload_to='video-banners'),
        ),
    ]
